[tool.poetry]
name = "aiosql"
version = "3.0.0"
description = "Simple SQL in Python."
authors = ["William Vaughn <vaughnwilld@gmail.com>"]
license = "FreeBSD"
repository = "https://github.com/nackjicholson/aiosql"
readme = "README.md"
keywords = ["SQL", "asyncio", "PostgreSQL", "sqlite", "psycopg2"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.6"
pytest = "^5.4.1"
aiosqlite = "^0.11.0"
asyncpg = "^0.20.1"
sphinx = "^1.8"
invoke = "^1.2"
pytest-asyncio = "^0.10.0"
psycopg2-binary = "^2.8.4"
mypy = "^0.770"

[tool.black]
line-length = 100
py36 = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

